// Code generated by candi v1.18.4.

package repository

import (
	"context"
	"strings"
	"time"

	"example-ecommerce/internal/modules/user/domain"
	"example-ecommerce/pkg/shared"
	shareddomain "example-ecommerce/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/tracer"
	"github.com/google/uuid"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

type userRepoSQL struct {
	readDB, writeDB *gorm.DB
	updateTools     *candishared.DBUpdateTools
}

// NewUserRepoSQL repo constructor
func NewUserRepoSQL(readDB, writeDB *gorm.DB) UserRepository {
	return &userRepoSQL{
		readDB: readDB, writeDB: writeDB,
		updateTools: &candishared.DBUpdateTools{
			KeyExtractorFunc: candishared.DBUpdateGORMExtractorKey, IgnoredFields: []string{"id"},
		},
	}
}

func (r *userRepoSQL) FetchAll(ctx context.Context, filter *domain.FilterUser) (data []shareddomain.User, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "UserRepoSQL:FetchAll")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	if filter.OrderBy == "" {
		filter.OrderBy = "updated_at"
	}

	db := r.setFilterUser(shared.SetSpanToGorm(ctx, r.readDB), filter).Order(clause.OrderByColumn{
		Column: clause.Column{Name: filter.OrderBy},
		Desc:   strings.ToUpper(filter.Sort) == "DESC",
	})
	if filter.Limit > 0 || !filter.ShowAll {
		db = db.Limit(filter.Limit).Offset(filter.CalculateOffset())
	}
	err = db.Find(&data).Error
	return
}

func (r *userRepoSQL) Count(ctx context.Context, filter *domain.FilterUser) (count int) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "UserRepoSQL:Count")
	defer trace.Finish()

	var total int64
	r.setFilterUser(shared.SetSpanToGorm(ctx, r.readDB), filter).Model(&shareddomain.User{}).Count(&total)
	count = int(total)

	trace.Log("count", count)
	return
}

func (r *userRepoSQL) Find(ctx context.Context, filter *domain.FilterUser) (result shareddomain.User, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "UserRepoSQL:Find")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	err = r.setFilterUser(shared.SetSpanToGorm(ctx, r.readDB), filter).First(&result).Error
	return
}

func (r *userRepoSQL) Save(ctx context.Context, data *shareddomain.User, updateOptions ...candishared.DBUpdateOptionFunc) (id uuid.UUID, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "UserRepoSQL:Save")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	data.UpdatedAt = time.Now()
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}

	txDB := new(gorm.DB)
	if data.ID == uuid.Nil {
		data.ID = uuid.New()
		txDB = shared.SetSpanToGorm(ctx, db).Omit(clause.Associations).Create(data)
	} else {
		txDB = shared.SetSpanToGorm(ctx, db).Model(data).Omit(clause.Associations).Updates(r.updateTools.ToMap(data, updateOptions...))
	}

	if txDB.Error != nil {
		err = txDB.Error
		return
	}

	id = data.ID

	return
}

func (r *userRepoSQL) Delete(ctx context.Context, filter *domain.FilterUser) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "UserRepoSQL:Delete")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	err = r.setFilterUser(shared.SetSpanToGorm(ctx, db), filter).Delete(&shareddomain.User{}).Error
	return
}

func (r *userRepoSQL) setFilterUser(db *gorm.DB, filter *domain.FilterUser) *gorm.DB {
	if filter.ID != "" {
		db = db.Where("id = ?", filter.ID)
	}
	if filter.PhoneNumber != "" {
		db = db.Where("phone_number = ?", filter.PhoneNumber)
	}
	if filter.Search != "" {
		db = db.Where("(first_name ILIKE '%%' || ? || '%%')", filter.Search)
		db = db.Or("(last_name ILIKE '%%' || ? || '%%')", filter.Search)
	}

	for _, preload := range filter.Preloads {
		db = db.Preload(preload)
	}

	return db
}
