// Code generated by candi v1.18.4.

package repository

import (
	"context"

	"example-ecommerce/internal/modules/user/domain"
	shareddomain "example-ecommerce/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
	"github.com/google/uuid"
)

// UserRepository abstract interface
type UserRepository interface {
	FetchAll(ctx context.Context, filter *domain.FilterUser) ([]shareddomain.User, error)
	Count(ctx context.Context, filter *domain.FilterUser) int
	Find(ctx context.Context, filter *domain.FilterUser) (shareddomain.User, error)
	Save(ctx context.Context, data *shareddomain.User, updateOptions ...candishared.DBUpdateOptionFunc) (id uuid.UUID, err error)
	Delete(ctx context.Context, filter *domain.FilterUser) (err error)
}
