// Code generated by candi v1.18.4.

package usecase

import (
	"sync"

	// @candi:usecaseImport
	orderusecase "example-ecommerce/internal/modules/order/usecase"
	userusecase "example-ecommerce/internal/modules/user/usecase"

	// paymentusecase "example-ecommerce/internal/modules/payment/usecase"
	"example-ecommerce/pkg/shared/usecase/common"

	"github.com/golangid/candi/codebase/factory/dependency"
)

type (
	// Usecase unit of work for all usecase in modules
	Usecase interface {
		// @candi:usecaseMethod
		Order() orderusecase.OrderUsecase
		User() userusecase.UserUsecase
		// Payment() paymentusecase.PaymentUsecase
	}

	usecaseUow struct {
		// @candi:usecaseField
		orderusecase.OrderUsecase
		userusecase.UserUsecase
		// paymentusecase.PaymentUsecase
	}
)

var usecaseInst *usecaseUow
var once sync.Once

// SetSharedUsecase set singleton usecase unit of work instance
func SetSharedUsecase(deps dependency.Dependency) {
	once.Do(func() {
		usecaseInst = new(usecaseUow)
		var setSharedUsecaseFuncs []func(common.Usecase)
		var setSharedUsecaseFunc func(common.Usecase)

		// @candi:usecaseCommon
		usecaseInst.OrderUsecase, setSharedUsecaseFunc = orderusecase.NewOrderUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)
		usecaseInst.UserUsecase, setSharedUsecaseFunc = userusecase.NewUserUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)
		// usecaseInst.PaymentUsecase, setSharedUsecaseFunc = paymentusecase.NewPaymentUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)

		sharedUsecase := common.SetCommonUsecase(usecaseInst)
		for _, setFunc := range setSharedUsecaseFuncs {
			setFunc(sharedUsecase)
		}
	})
}

// GetSharedUsecase get usecase unit of work instance
func GetSharedUsecase() Usecase {
	return usecaseInst
}

// @candi:usecaseImplementation
func (uc *usecaseUow) Order() orderusecase.OrderUsecase {
	return uc.OrderUsecase
}

func (uc *usecaseUow) User() userusecase.UserUsecase {
	return uc.UserUsecase
}

// func (uc *usecaseUow) Payment() paymentusecase.PaymentUsecase {
// 	return uc.PaymentUsecase
// }
