// Code generated by candi v1.18.4.

package shared

// Environment additional in this service
type Environment struct {
	// more additional environment with struct tag is environment key example:
	// ExampleHost string `env:"EXAMPLE_HOST"`

	AccessTokenAge  string `env:"ACCESS_TOKEN_AGE"`
	RefreshTokenAge string `env:"REFRESH_TOKEN_AGE"`
	RetryCount      int    `env:"TASK_QUEUE_RETRY_COUNT"`
}

var sharedEnv Environment

// GetEnv get global additional environment
func GetEnv() Environment {
	return sharedEnv
}

// SetEnv get global additional environment
func SetEnv(env Environment) {
	sharedEnv = env
}
